[helpers]

[default]
depends = []

[default.files]
"README.md" = ""
"global.toml" = ""
"local.toml" = ""
".gitignore_global" = "~/.gitignore_global"
"emacs" = "~/.emacs.d"

[default.variables]

[settings]
default_target_type = "automatic"
