[helpers]

[default]
depends = []

[default.files]
"README.md" = ""
"global.toml" = ""
"local.toml" = ""
".emacs.d" = "~/.emacs.d"
".config/fish/config.fish" = "~/.config/fish/config.fish"
".config/fish/completions/fisher.fish" = "~/.config/fish/completions/fisher.fish"
".config/fish/fish_plugins" = "~/.config/fish/fish_plugins"
".config/fish/fish_variables" = "~/.config/fish/fish_variables"
".config/fish/functions/fish_prompt.fish" = "~/.config/fish/functions/fish_prompt.fish"
".config/fish/functions/fisher.fish" = "~/.config/fish/functions/fisher.fish"

[default.variables]

[settings]
default_target_type = "automatic"
